server:
  port: 5678

jwt:
  secret-key: XkkTy12

inputfile:
  user-name: classpath:dataset/user.csv
  room-name: classpath:dataset/room.csv
  animal-name: classpath:dataset/animal.csv
load:
  default-data: true

spring:
  application:
    name: zoo
  datasource:
    url: jdbc:mysql://localhost:3306/zooeurail?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=ECT&createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.enable_lazy_load_no_trans: false
    database: mysql
logging:
  level:
    root: INFO
  file:
    path: logs/
    name: logs/zoo.log
