server:
  port: 5678

jwt:
  secret-key: XkkTy12

inputfile:
  user-name: classpath:dataset/user.csv


spring:
  application:
    name: zoo
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb?serverTimezone=ECT&useLegacyDatetimeCode=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
logging:
  level:
    root: INFO
  file:
    path: logs/
    name: logs/zoo.log
simulate:
  sensor-data: true
