server:
  port: 5678

jwt:
  secret-key: XkkTy12

inputfile:
  user-name: classpath:dataset/user.csv
  room-name: classpath:dataset/room.csv
  animal-name: classpath:dataset/animal.csv


spring:
  application:
    name: zoo
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb?serverTimezone=ECT&useLegacyDatetimeCode=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    properties:
      hibernate.enable_lazy_load_no_trans: false
logging:
  level:
    root: INFO
  file:
    path: logs/
    name: logs/zoo.log
simulate:
  sensor-data: true
